DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

-- 글번호 그룹번호 그룹순서 제목공백 젬고 내용 작성자 작성일
CREATE TABLE ANSWERBOARD (

	BOARDNO NUMBER PRIMARY KEY,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL

);
-- 1번글 작성
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, 
       '1번글 입니다.', '1번 글을 썻는데...답변형어렵다','강사', SYSDATE);

-- 1번글에 답변 작성
-- UPDATE
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = ?)
AND GORUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = ?);
       
-- INSERT
       
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, 
	  (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1),
	  (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1) + 1,
	  (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 1) + 1,
      'RE:1번글에 답변',
      '답변',
      '무플방지위원회',
      SYSDATE);
-- 2번글 작성

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, '2번글 입니다.', '2번 원글', '반장', SYSDATE);

-- 2번글 답변
-- UPDATE
-- INSERT
-- 그룹번호 : 답변을 달려고 하는 부모글의 그룹번호
-- 그룹순서 : 답변을 달려고 하는 부모글의 그룹순서 + 1
-- 제목공백 : 답변을 달려고 하는 부모글의 제목공백 + 1

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
	  (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=3),
	  (SELECT GROUPSEQ +1 FROM ANSWERBOARD WHERE BOARDNO=3),
	  (SELECT TITLETAB +1 FROM ANSWERBOARD WHERE BOARDNO=3),
	  'RE:2번글 답변',
	  '답변',
	  '무플방지위원회장',
	  SYSDATE);
	  
-- 2번글 답변에 답변
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
	  (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=4),
	  (SELECT GROUPSEQ +1 FROM ANSWERBOARD WHERE BOARDNO=4),
	  (SELECT TITLETAB +1 FROM ANSWERBOARD WHERE BOARDNO=4),
	  'RE:RE:2번글 답변의 답변',
	  '답변의 답변',
	  '무플방지위원회장의 아내',
	  SYSDATE);
	  
-- 2번글 원글에 답변 다시 달기
-- UPDATE
-- 부모와 같은 그룹인 글들을 찾아서, 부모의 순서 + 1
UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 3)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 3);

-- INSERT
INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
	  (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO=3),
	  (SELECT GROUPSEQ +1 FROM ANSWERBOARD WHERE BOARDNO=3),
	  (SELECT TITLETAB +1 FROM ANSWERBOARD WHERE BOARDNO=3),
	  'RE:2번글 입니다.',
	  '이제 더 어렵네',
	  '학생',
	  SYSDATE);

-- 출력
SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, TITLE, CONTENT, WRITER, REGDATE
FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSEQ;