DROP SEQUENCE YJBOARDSEQ;
DROP TABLE YJBOARD;

CREATE SEQUENCE YJBOARDSEQ;

CREATE TABLE YJBOARD (

	SEQ NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	REGDATE DATE NOT NULL

);

INSERT INTO YJBOARD
VALUES (YJBOARDSEQ.NEXTVAL, '이용준', '다시만들기', '다시만들기 힘들다', SYSDATE);

INSERT INTO YJBOARD
VALUES (YJBOARDSEQ.NEXTVAL, '이용준2', '다시만들기2', '다시만들기 개힘들다', SYSDATE);

SELECT SEQ, WRITER, TITLE, CONTENT, REGDATE
FROM YJBOARD
ORDER BY SEQ DESC;