DROP SEQUENCE BOARDNOSEQ;
DROP SEQUENCE GROUPNOSEQ;
DROP TABLE ANSWERBOARD;

CREATE SEQUENCE BOARDNOSEQ;
CREATE SEQUENCE GROUPNOSEQ;

CREATE TABLE ANSWERBOARD (

	BOARDNO NUMBER NOT NULL,
	GROUPNO NUMBER NOT NULL,
	GROUPSEQ NUMBER NOT NULL,
	TITLETAB NUMBER NOT NULL,
	DELFLAG VARCHAR2(2) NOT NULL,
	TITLE VARCHAR2(1000) NOT NULL,
	CONTENT VARCHAR2(4000) NOT NULL,
	WRITER VARCHAR2(100) NOT NULL,
	REGDATE DATE NOT NULL,
	
	CONSTRAINT ANSWER_BOARDNO_PK PRIMARY KEY(BOARDNO),
	CONSTRAINT ANSWER_DELFLAG_CHECK CHECK(DELFLAG IN('Y','N'))

);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL, GROUPNOSEQ.NEXTVAL, 1, 0, 'N', '답변형재밌다', '정말재밌다','반장', SYSDATE);

UPDATE ANSWERBOARD
SET GROUPSEQ = GROUPSEQ + 1
WHERE GROUPNO = (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1)
AND GROUPSEQ > (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1);

INSERT INTO ANSWERBOARD
VALUES(BOARDNOSEQ.NEXTVAL,
       (SELECT GROUPNO FROM ANSWERBOARD WHERE BOARDNO = 1),
       (SELECT GROUPSEQ FROM ANSWERBOARD WHERE BOARDNO = 1) + 1,
       (SELECT TITLETAB FROM ANSWERBOARD WHERE BOARDNO = 1) + 1,
       'N', '답변복습하기', '너무 헷갈려~','이용준', SYSDATE);

SELECT BOARDNO, GROUPNO, GROUPSEQ, TITLETAB, DELFLAG, TITLE, CONTENT, WRITER, REGDATE
FROM ANSWERBOARD
ORDER BY GROUPNO DESC, GROUPSEQ;

UPDATE ANSWERBOARD
SET TITLE = 'RE:답변복습하기'
WHERE BOARDNO = 2;